services:
  api:
    build: ./api
    container_name: lapiz-de-encanto-api
    ports:
      - "4000:4000"
    volumes:
      - db_data:/app/data
      - ./api/static:/app/static
    env_file:
      - ./api/.env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4000/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: lapiz-de-encanto-frontend
    ports:
      - "3000:3000"
    depends_on:
      api:
        condition: service_healthy
    env_file:
      - ./frontend/.env
    restart: unless-stopped

  admin:
    build: ./admin
    container_name: lapiz-de-encanto-admin
    ports:
      - "3001:3001"
    depends_on:
      api:
        condition: service_healthy
    env_file:
      - ./admin/.env

    restart: unless-stopped

volumes:
  db_data:
