services:
  lde-api:
    volumes:
      - ./lde-api:/app
    working_dir: /app
    command: sh -c "ls -l /app && /app/start.sh"
    ports:
      - 4000:4000
    environment:
      - PYTHONUNBUFFERED=1
  lde-admin:
    volumes:
      - ./lde-admin:/workspace/lde-admin
    command: sh -c "cd /workspace/lde-admin && npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - 3001:3001
  lde-frontend:
    volumes:
      - ./lde-frontend:/workspace/lde-frontend
    command: sh -c "cd /workspace/lde-frontend && npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - 3000:3000
